### ISSUE TITLE
RFC: TicketTableViewCell as a NIB

### ISSUE THREAD

**Issue by kruppel** [kencheeto/triage#22]
Do people want this? /cc @shanitang @kencheeto 

I initially added it, but found it easier to just add to the storyboard. We can extract it and add the NIB back though, if that's everyone's preference.

**Comment by kencheeto** [comment]
Maybe it's a good way to encapsulate the IB work for different cell subviews (#26)? Do you think there are advantages elsewhere?

**Comment by kruppel** [comment]
I think there's marginal benefit, but it's probably the conventional way to implement a custom view class.
