### ISSUE TITLE
animate swipe complete

### ISSUE THREAD

**Issue by kencheeto** [kencheeto/triage#30]
If we're in an actionable swipe zone when released, the cell should slide horizontally off the screen

**Comment by kruppel** [comment]
![remove_on_swipe](https://cloud.githubusercontent.com/assets/279376/6547982/dcc81c5a-c5a6-11e4-9f7c-e7bdf6e318a7.gif)

**Comment by kruppel** [comment]
Closed by bd376ea02c24c10b4725c67cc848d6de08abdd93 .
