### ISSUE TITLE
add visual cues for swipes

### ISSUE THREAD

**Issue by kintner** [kencheeto/triage#52]

**Comment by kencheeto** [comment]
@corinnader would be cool to have icons or something that reveal when you start swiping a ticket cell? 

![screen shot 2015-03-11 at 4 21 37 pm](https://cloud.githubusercontent.com/assets/279406/6609093/bf88fbc6-c80a-11e4-9689-0aca74e6532f.png)
![screen shot 2015-03-11 at 4 21 42 pm](https://cloud.githubusercontent.com/assets/279406/6609094/c2a56984-c80a-11e4-8aca-a1df1daf7f24.png)
