### ISSUE TITLE
Fix infinite scroll

### ISSUE THREAD

**Issue by kruppel** [kencheeto/triage#55]

**Comment by kintner** [comment]
what's wrong with scrolling?

**Comment by kruppel** [comment]
The next page wasn't loading for me once I hit the bottom of the list.

**Comment by kintner** [comment]
Huh - that was working for me on Tuesday. The tablecell refactor may have
broken it.

**Comment by kintner** [comment]
@kruppel it's currently working for me. Can you still reproduce?
